if (NOT DEFINED FRAMELIFT_ROOT OR NOT DEFINED TEST_ROOT)
    message(FATAL_ERROR "FRAMELIFT_ROOT and TEST_ROOT are required")
endif ()

file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")
file(WRITE "${TEST_ROOT}/framelift.current.so" "current")
file(WRITE "${TEST_ROOT}/framelift.renamed.so" "obsolete")
file(WRITE "${TEST_ROOT}/example.third_party.so" "third-party")

set(PLUGIN_DIR "${TEST_ROOT}")
set(PLUGIN_SUFFIX ".so")
set(EXPECTED_PLUGIN_FILES "framelift.current.so")
include("${FRAMELIFT_ROOT}/cmake/PrunePluginOutput.cmake")

if (NOT EXISTS "${TEST_ROOT}/framelift.current.so")
    message(FATAL_ERROR "Current first-party plugin was removed")
endif ()
if (EXISTS "${TEST_ROOT}/framelift.renamed.so")
    message(FATAL_ERROR "Obsolete first-party plugin was preserved")
endif ()
if (NOT EXISTS "${TEST_ROOT}/example.third_party.so")
    message(FATAL_ERROR "Third-party plugin was removed")
endif ()
