#pragma once

#include <framelift/IModule.h>
#include <framelift/IRenderable.h>
#include <framelift/Log.h>

#include <QtCore/QtPlugin>

// The single interface a package DLL's root object implements. A package is loaded
// with QPluginLoader: the host first reads the package's identity + ABI from the
// embedded Q_PLUGIN_METADATA JSON (no instantiation, no vtable touched), and only
// for an ABI-compatible, dependency-satisfied package does it call instance() and
// qobject_cast<IPackage*> the root object. It then drives each module the package
// carries BY ITS MODULE ID, mirroring the old framelift_* C exports:
//
//   SetLogSink   — wire the package's per-module log sink to the host logger.
//   CreateModule — factory for the module with the given id (nullptr on failure).
//   DestroyModule— delete a module created by CreateModule.
//   GetRenderable— the module as an IRenderable*, or nullptr if it draws nothing.
//   RenderOrder  — z-order for a renderable module.
//
// The concrete root object is generated by FRAMELIFT_MODULE_ENTRY /
// FRAMELIFT_PACKAGE_* (see ModuleEntry.h): a QObject that multiply-inherits this
// interface, declares Q_INTERFACES(IPackage), and carries the Q_PLUGIN_METADATA.
class IPackage
{
public:
    virtual ~IPackage() = default;

    virtual void SetLogSink(Log::SinkFn fn) noexcept = 0;
    virtual IModule* CreateModule(const char* moduleId) noexcept = 0;
    virtual void DestroyModule(IModule* module) noexcept = 0;
    virtual IRenderable* GetRenderable(const char* moduleId, IModule* module) noexcept = 0; // nullptr if none
    virtual int RenderOrder(const char* moduleId) noexcept = 0;
};

// Interface id used by Q_PLUGIN_METADATA on the plugin side and qobject_cast on the
// host side. Bump the trailing version only if IPackage's own signature changes
// (a Tier-1 break that also bumps FRAMELIFT_ABI_VERSION).
#define FrameLiftPackage_IID "org.framelift.IPackage/1"
Q_DECLARE_INTERFACE(IPackage, FrameLiftPackage_IID)
