#pragma once

#include <framelift/IModule.h>
#include <framelift/Log.h>

#include <QtCore/QtPlugin>

class QObject;

// The single interface a runtime plugin's root object implements. A plugin is loaded
// with QPluginLoader: the host first reads the plugin's identity + ABI from the
// embedded Q_PLUGIN_METADATA JSON (no instantiation, no vtable touched), and only
// for an ABI-compatible, dependency-satisfied plugin does it call instance() and
// qobject_cast<IPlugin*> the root object. Each plugin owns exactly one IModule:
//
//   SetLogSink   — wire the plugin's log sink to the host logger.
//   CreateModule — factory for the plugin's module (nullptr on failure).
//   DestroyModule— delete the module created by CreateModule.
//   GetViewModel — the module as a QObject exposed to QML, or nullptr for service-only modules.
//   QmlEntryUrl  — qrc URL of the module's root QML component, or nullptr.
//   RenderOrder  — z-order for a QML module.
//
// The concrete root object is generated by FRAMELIFT_MODULE_ENTRY (see
// ModuleEntry.h): a QObject that multiply-inherits this interface, declares
// Q_INTERFACES(IPlugin), and carries the Q_PLUGIN_METADATA.
class IPlugin
{
public:
    virtual ~IPlugin() = default;

    virtual void SetLogSink(Log::SinkFn fn) noexcept = 0;
    virtual IModule* CreateModule() noexcept = 0;
    virtual void DestroyModule(IModule* module) noexcept = 0;
    virtual QObject* GetViewModel(IModule* module) noexcept = 0;
    virtual const char* QmlEntryUrl() noexcept = 0;
    virtual int RenderOrder() noexcept = 0;
};

// Interface id used by Q_PLUGIN_METADATA on the plugin side and qobject_cast on the
// host side. Bump the trailing version only if IPlugin's own signature changes
// (a Tier-1 break; this Qt migration branch intentionally keeps
// FRAMELIFT_ABI_VERSION at 1 while host/plugins rebuild together).
#define FrameLiftPlugin_IID "org.framelift.IPlugin/2"
Q_DECLARE_INTERFACE(IPlugin, FrameLiftPlugin_IID)
