#pragma once
#include <framelift/IModule.h>
#include <framelift/IRenderable.h>
#include <framelift/Log.h>
#include <framelift/ModuleABI.h>

#include <cstring>
#include <exception>
#include <type_traits>

#ifndef FRAMELIFT_MODULE_METADATA_HEADER
#error "FRAMELIFT_MODULE_METADATA_HEADER must name the CMake-generated package metadata header"
#endif

#include FRAMELIFT_MODULE_METADATA_HEADER

#ifndef FRAMELIFT_MODULE_METADATA
#error "Generated package metadata header must define FRAMELIFT_MODULE_METADATA"
#endif

// A package DLL exports a fixed set of extern "C" entry points. The host calls
// framelift_module_info() first (ABI/identity, no vtable touched), then drives
// each module the package carries BY ITS MODULE ID:
//
//   extern "C" {
//     const FrameLiftPackageInfo* framelift_module_info();
//     void         framelift_set_log_sink(Log::SinkFn);
//     IModule*     framelift_create(const char* moduleId);
//     void         framelift_destroy(IModule*);
//     IRenderable* framelift_get_renderable(const char* moduleId, IModule*); // nullptr if not renderable
//     int          framelift_render_order(const char* moduleId);              // z-order for renderables
//   }
//
// Package/module identity comes from the JSON-authored metadata header generated by
// add_framelift_plugin(... PLUGIN_JSON <file>). The C++ macros below only carry the
// runtime traits that depend on the concrete module entry types (the factory, the
// renderable cast, the render order).
//
// Single-module package — the common case:
//
//   FRAMELIFT_MODULE_ENTRY(MyPanel, {
//       .renderOrder = 50,
//   })
//
// A module that draws nothing opts out of rendering explicitly:
//
//   FRAMELIFT_MODULE_ENTRY(MyService, {
//       .render = false,
//   })
//
// Multi-module package — one DLL carrying several modules. Each FRAMELIFT_MODULE id
// must match an id declared in the package's .Module.json set:
//
//   FRAMELIFT_PACKAGE_BEGIN()
//     FRAMELIFT_MODULE("framelift.overlay.core",     OverlayCore,     { .renderOrder = 0 })
//     FRAMELIFT_MODULE("framelift.overlay.settings", OverlaySettings, { .render = false })
//   FRAMELIFT_PACKAGE_END()

struct FrameLiftModuleEntryDesc
{
    bool render = true;
    int renderOrder = 0;
};

#ifdef _WIN32
#define FRAMELIFT_MODULE_API __declspec(dllexport)
#else
#define FRAMELIFT_MODULE_API __attribute__((visibility("default")))
#endif

namespace framelift::detail
{
template <typename T>
IRenderable* GetRenderable(IModule* p)
{
    if constexpr (std::is_base_of_v<IRenderable, T>)
    {
        return static_cast<T*>(p);
    }
    else
    {
        return nullptr;
    }
}

template <typename T>
IModule* CreateModule()
{
    try
    {
        return new T();
    }
    catch (const std::exception& e)
    {
        Log::Error("{}: constructor threw: {}", FRAMELIFT_MODULE_METADATA.name, e.what());
    }
    catch (...)
    {
        Log::Error("{}: constructor threw a non-standard exception", FRAMELIFT_MODULE_METADATA.name);
    }
    return nullptr;
}

// One row per module the package carries: the module id (the dispatch key) plus the
// type-erased factory and renderable cast for that module's concrete entry type.
struct ModuleTableEntry
{
    const char* id;
    IModule* (*create)();
    IRenderable* (*getRenderable)(IModule*);
    int renderOrder;
    bool render;
};

inline const ModuleTableEntry* FindModule(const ModuleTableEntry* table, int count, const char* id)
{
    if (id)
    {
        for (int i = 0; i < count; ++i)
        {
            if (table[i].id && std::strcmp(table[i].id, id) == 0)
            {
                return &table[i];
            }
        }
    }
    // A single-module package serves its lone module for any requested id, so a
    // host that doesn't bother passing the id (or passes a stale one) still works.
    return count == 1 ? &table[0] : nullptr;
}
} // namespace framelift::detail

// Shared body of the six extern "C" exports, dispatching against a module table.
#define FRAMELIFT_DETAIL_MODULE_EXPORTS(Table, Count)                                                                   \
    extern "C"                                                                                                          \
    {                                                                                                                   \
        FRAMELIFT_MODULE_API const FrameLiftPackageInfo* framelift_module_info()                                        \
        {                                                                                                               \
            return &FRAMELIFT_MODULE_METADATA;                                                                          \
        }                                                                                                               \
        FRAMELIFT_MODULE_API void framelift_set_log_sink(Log::SinkFn fn)                                                \
        {                                                                                                               \
            Log::SetSink(fn);                                                                                           \
        }                                                                                                               \
        FRAMELIFT_MODULE_API IModule* framelift_create(const char* moduleId)                                           \
        {                                                                                                               \
            const ::framelift::detail::ModuleTableEntry* e = ::framelift::detail::FindModule((Table), (Count), moduleId); \
            return e ? e->create() : nullptr;                                                                          \
        }                                                                                                               \
        FRAMELIFT_MODULE_API void framelift_destroy(IModule* f)                                                         \
        {                                                                                                               \
            delete f;                                                                                                   \
        }                                                                                                               \
        FRAMELIFT_MODULE_API IRenderable* framelift_get_renderable(const char* moduleId, IModule* f)                    \
        {                                                                                                               \
            const ::framelift::detail::ModuleTableEntry* e = ::framelift::detail::FindModule((Table), (Count), moduleId); \
            return (e && e->render && e->getRenderable) ? e->getRenderable(f) : nullptr;                                \
        }                                                                                                               \
        FRAMELIFT_MODULE_API int framelift_render_order(const char* moduleId)                                          \
        {                                                                                                               \
            const ::framelift::detail::ModuleTableEntry* e = ::framelift::detail::FindModule((Table), (Count), moduleId); \
            return (e && e->render) ? e->renderOrder : 0;                                                               \
        }                                                                                                               \
    }

// One table row from a module id, its entry type, and the runtime descriptor. The
// descriptor (FrameLiftModuleEntryDesc) is evaluated as a temporary; a non-renderable
// Type compiled with .render = true is harmless (GetRenderable returns nullptr).
#define FRAMELIFT_MODULE(ModuleId, Type, ...)                                                                          \
    {ModuleId, &::framelift::detail::CreateModule<Type>, &::framelift::detail::GetRenderable<Type>,                     \
     (::FrameLiftModuleEntryDesc __VA_ARGS__).renderOrder, (::FrameLiftModuleEntryDesc __VA_ARGS__).render},

#ifdef FRAMELIFT_SUPPRESS_MODULE_ENTRY
#define FRAMELIFT_MODULE_ENTRY(Type, ...)
#define FRAMELIFT_PACKAGE_BEGIN()
#define FRAMELIFT_PACKAGE_END()
#else
// Single-module convenience: builds a one-row table and emits the exports. The id is
// taken from the generated metadata, so the source stays free of the module id string.
#define FRAMELIFT_MODULE_ENTRY(Type, ...)                                                                              \
    namespace framelift_module_detail                                                                                  \
    {                                                                                                                  \
    inline constexpr ::FrameLiftModuleEntryDesc kDesc = __VA_ARGS__;                                                   \
    static_assert(                                                                                                     \
        !kDesc.render || std::is_base_of_v<IRenderable, Type>,                                                         \
        "FRAMELIFT_MODULE_ENTRY: " #Type " does not implement IRenderable; add .render = false or derive IRenderable"  \
    );                                                                                                                 \
    inline const ::framelift::detail::ModuleTableEntry kModuleTable[] = {                                              \
        {FRAMELIFT_MODULE_METADATA.modules[0].id, &::framelift::detail::CreateModule<Type>,                            \
         &::framelift::detail::GetRenderable<Type>, kDesc.renderOrder, kDesc.render}};                                 \
    }                                                                                                                  \
    FRAMELIFT_DETAIL_MODULE_EXPORTS(framelift_module_detail::kModuleTable, 1)

// Multi-module package: FRAMELIFT_PACKAGE_BEGIN(), one FRAMELIFT_MODULE(...) per
// carried module, then FRAMELIFT_PACKAGE_END().
#define FRAMELIFT_PACKAGE_BEGIN()                                                                                      \
    namespace framelift_module_detail                                                                                  \
    {                                                                                                                  \
    inline const ::framelift::detail::ModuleTableEntry kModuleTable[] = {

#define FRAMELIFT_PACKAGE_END()                                                                                        \
    }                                                                                                                  \
    ;                                                                                                                  \
    inline constexpr int kModuleCount = static_cast<int>(sizeof(kModuleTable) / sizeof(kModuleTable[0]));              \
    }                                                                                                                  \
    FRAMELIFT_DETAIL_MODULE_EXPORTS(framelift_module_detail::kModuleTable, framelift_module_detail::kModuleCount)
#endif
