# JSON-authored plugin metadata -> embedded Qt plugin metadata.

if (NOT DEFINED FRAMELIFT_SDK_ABI_VERSION)
    set(_framelift_abi_header_candidates
            "${CMAKE_CURRENT_LIST_DIR}/../sdk/include/framelift/ModuleABI.h"
            "${CMAKE_CURRENT_LIST_DIR}/../include/framelift/ModuleABI.h")
    set(_framelift_abi_header "")
    foreach (_candidate IN LISTS _framelift_abi_header_candidates)
        if (EXISTS "${_candidate}")
            set(_framelift_abi_header "${_candidate}")
            break()
        endif ()
    endforeach ()
    if ("${_framelift_abi_header}" STREQUAL "")
        message(FATAL_ERROR "Unable to find ModuleABI.h for plugin metadata generation")
    endif ()
    file(READ "${_framelift_abi_header}" _framelift_plugin_abi_h)
    if (_framelift_plugin_abi_h MATCHES "#define[ \t]+FRAMELIFT_ABI_VERSION[ \t]+([0-9]+)")
        set(FRAMELIFT_SDK_ABI_VERSION "${CMAKE_MATCH_1}")
    else ()
        message(FATAL_ERROR "Unable to parse FRAMELIFT_ABI_VERSION from ModuleABI.h")
    endif ()
endif ()

function(_framelift_json_required_string out json path label)
    string(JSON _value ERROR_VARIABLE _err GET "${json}" ${path})
    if (_err)
        message(FATAL_ERROR "${label}: missing required string '${path}' (${_err})")
    endif ()
    set(${out} "${_value}" PARENT_SCOPE)
endfunction()

function(_framelift_json_optional_string out json path default)
    string(JSON _value ERROR_VARIABLE _err GET "${json}" ${path})
    if (_err)
        set(_value "${default}")
    endif ()
    set(${out} "${_value}" PARENT_SCOPE)
endfunction()

function(_framelift_json_required_bool out json path label)
    string(JSON _value ERROR_VARIABLE _err GET "${json}" ${path})
    if (_err)
        message(FATAL_ERROR "${label}: missing required bool '${path}' (${_err})")
    endif ()
    if (NOT _value STREQUAL "ON" AND NOT _value STREQUAL "OFF" AND
        NOT _value STREQUAL "true" AND NOT _value STREQUAL "false")
        message(FATAL_ERROR "${label}: '${path}' must be a boolean")
    endif ()
    if (_value STREQUAL "true" OR _value STREQUAL "ON")
        set(${out} TRUE PARENT_SCOPE)
    else ()
        set(${out} FALSE PARENT_SCOPE)
    endif ()
endfunction()

function(_framelift_json_optional_bool out json path default label)
    string(JSON _value ERROR_VARIABLE _err GET "${json}" ${path})
    if (_err)
        set(_value "${default}")
    endif ()
    if (NOT _value STREQUAL "ON" AND NOT _value STREQUAL "OFF" AND
        NOT _value STREQUAL "true" AND NOT _value STREQUAL "false")
        message(FATAL_ERROR "${label}: '${path}' must be a boolean")
    endif ()
    if (_value STREQUAL "true" OR _value STREQUAL "ON")
        set(${out} TRUE PARENT_SCOPE)
    else ()
        set(${out} FALSE PARENT_SCOPE)
    endif ()
endfunction()

function(_framelift_json_required_int out json path label)
    string(JSON _value ERROR_VARIABLE _err GET "${json}" ${path})
    if (_err)
        message(FATAL_ERROR "${label}: missing required integer '${path}' (${_err})")
    endif ()
    if (NOT "${_value}" MATCHES "^[0-9]+$")
        message(FATAL_ERROR "${label}: '${path}' must be an integer")
    endif ()
    set(${out} "${_value}" PARENT_SCOPE)
endfunction()

function(_framelift_json_string_array out json label)
    set(_items)
    string(JSON _length ERROR_VARIABLE _err LENGTH "${json}" ${ARGN})
    if (_err)
        set(${out} "" PARENT_SCOPE)
        return()
    endif ()
    if (_length GREATER 0)
        math(EXPR _last "${_length} - 1")
        foreach (_i RANGE 0 ${_last})
            string(JSON _item ERROR_VARIABLE _item_err GET "${json}" ${ARGN} ${_i})
            if (_item_err)
                message(FATAL_ERROR "${label}: invalid string array item '${ARGN}[${_i}]' (${_item_err})")
            endif ()
            list(APPEND _items "${_item}")
        endforeach ()
    endif ()
    set(${out} "${_items}" PARENT_SCOPE)
endfunction()

function(_framelift_cpp_string out value)
    if ("${value}" STREQUAL "")
        set(${out} "\"\"" PARENT_SCOPE)
        return()
    endif ()
    string(REPLACE "\\" "\\\\" _value "${value}")
    string(REPLACE "\"" "\\\"" _value "${_value}")
    set(${out} "\"${_value}\"" PARENT_SCOPE)
endfunction()

function(_framelift_cpp_optional_string out value)
    if ("${value}" STREQUAL "")
        set(${out} "nullptr" PARENT_SCOPE)
    else ()
        _framelift_cpp_string(_quoted "${value}")
        set(${out} "${_quoted}" PARENT_SCOPE)
    endif ()
endfunction()

function(_framelift_json_escape out value)
    string(REPLACE "\\" "\\\\" _value "${value}")
    string(REPLACE "\"" "\\\"" _value "${_value}")
    set(${out} "${_value}" PARENT_SCOPE)
endfunction()

function(_framelift_json_string out value)
    _framelift_json_escape(_escaped "${value}")
    set(${out} "\"${_escaped}\"" PARENT_SCOPE)
endfunction()

function(_framelift_json_optional_string_or_null out value)
    if ("${value}" STREQUAL "")
        set(${out} "null" PARENT_SCOPE)
    else ()
        _framelift_json_string(_quoted "${value}")
        set(${out} "${_quoted}" PARENT_SCOPE)
    endif ()
endfunction()

# Render a CMake list as a JSON array of strings: () -> "[]", (a;b) -> "[\"a\",\"b\"]".
function(_framelift_json_string_array_expr out items)
    set(_values)
    foreach (_item IN LISTS items)
        _framelift_json_string(_quoted "${_item}")
        list(APPEND _values "${_quoted}")
    endforeach ()
    list(JOIN _values "," _joined)
    set(${out} "[${_joined}]" PARENT_SCOPE)
endfunction()

function(_framelift_validate_file_version file_version label)
    if (NOT file_version EQUAL 1)
        message(FATAL_ERROR "${label}: unsupported fileVersion ${file_version}; expected 1")
    endif ()
endfunction()

function(_framelift_parse_version prefix version label)
    if ("${version}" STREQUAL "project")
        set(_version "${PROJECT_VERSION}")
    else ()
        set(_version "${version}")
    endif ()

    if (NOT _version MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$")
        message(FATAL_ERROR "${label}: version must be 'project' or a semantic version string X.Y.Z")
    endif ()

    set(${prefix}_MAJOR "${CMAKE_MATCH_1}" PARENT_SCOPE)
    set(${prefix}_MINOR "${CMAKE_MATCH_2}" PARENT_SCOPE)
    set(${prefix}_PATCH "${CMAKE_MATCH_3}" PARENT_SCOPE)
endfunction()

function(_framelift_parse_abi out version label)
    if (NOT "${version}" MATCHES "^[0-9]+$")
        message(FATAL_ERROR "${label}: abi must be a single integer version")
    endif ()

    if (NOT version EQUAL FRAMELIFT_SDK_ABI_VERSION)
        message(FATAL_ERROR
                "${label}: abi version ${version} does not match SDK ABI version ${FRAMELIFT_SDK_ABI_VERSION}")
    endif ()

    set(${out} "${version}" PARENT_SCOPE)
endfunction()

function(_framelift_pascal_from_id_tail out id)
    string(REGEX REPLACE "^.*\\." "" _tail "${id}")
    string(REGEX REPLACE "[^A-Za-z0-9]+" ";" _parts "${_tail}")
    set(_value "")
    foreach (_part IN LISTS _parts)
        if ("${_part}" STREQUAL "")
            continue()
        endif ()
        string(SUBSTRING "${_part}" 0 1 _first)
        string(SUBSTRING "${_part}" 1 -1 _rest)
        string(TOUPPER "${_first}" _first)
        string(APPEND _value "${_first}${_rest}")
    endforeach ()
    if ("${_value}" STREQUAL "")
        set(_value "${_tail}")
    endif ()
    set(${out} "${_value}" PARENT_SCOPE)
endfunction()

function(_framelift_current_platform out)
    if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(${out} "windows" PARENT_SCOPE)
    elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(${out} "macos" PARENT_SCOPE)
    elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(${out} "linux" PARENT_SCOPE)
    elseif (WIN32)
        set(${out} "windows" PARENT_SCOPE)
    elseif (APPLE)
        set(${out} "macos" PARENT_SCOPE)
    elseif (UNIX)
        set(${out} "linux" PARENT_SCOPE)
    else ()
        string(TOLOWER "${CMAKE_SYSTEM_NAME}" _platform)
        set(${out} "${_platform}" PARENT_SCOPE)
    endif ()
endfunction()

function(_framelift_emit_string_list out_code out_expr symbol items)
    set(_code "")
    if (items)
        set(_values)
        foreach (_item IN LISTS items)
            _framelift_cpp_string(_quoted "${_item}")
            list(APPEND _values "${_quoted}")
        endforeach ()
        list(JOIN _values ", " _joined)
        list(LENGTH items _count)
        string(APPEND _code "inline constexpr const char* const ${symbol}[] = {${_joined}};\n")
        set(${out_expr} "FrameLiftStringList{${symbol}, ${_count}}" PARENT_SCOPE)
    else ()
        set(${out_expr} "FrameLiftStringList{nullptr, 0}" PARENT_SCOPE)
    endif ()
    set(${out_code} "${_code}" PARENT_SCOPE)
endfunction()

function(_framelift_join_metadata_list out)
    set(_items ${ARGN})
    if (_items)
        string(JOIN "," _joined ${_items})
    else ()
        set(_joined "")
    endif ()
    set(${out} "${_joined}" PARENT_SCOPE)
endfunction()

function(_framelift_split_metadata_list out value)
    if ("${value}" STREQUAL "")
        set(${out} "" PARENT_SCOPE)
    else ()
        string(REPLACE "," ";" _items "${value}")
        set(${out} "${_items}" PARENT_SCOPE)
    endif ()
endfunction()

function(framelift_generate_plugin_metadata target plugin_json out_header out_enabled out_plugin_id out_plugin_binary_name)
    get_filename_component(_plugin_json_abs "${plugin_json}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if (NOT EXISTS "${_plugin_json_abs}")
        message(FATAL_ERROR "${target}: plugin metadata file not found: ${_plugin_json_abs}")
    endif ()

    file(READ "${_plugin_json_abs}" _plugin_json)
    _framelift_json_required_int(_plugin_file_version "${_plugin_json}" "fileVersion" "${target}")
    _framelift_validate_file_version("${_plugin_file_version}" "${target}")
    _framelift_json_required_string(_plugin_id "${_plugin_json}" "id" "${target}")
    _framelift_json_required_string(_plugin_name "${_plugin_json}" "name" "${target}")
    _framelift_json_optional_string(_plugin_publisher "${_plugin_json}" "publisher" "")
    _framelift_json_optional_string(_plugin_description "${_plugin_json}" "description" "")
    _framelift_json_required_string(_plugin_version "${_plugin_json}" "version" "${target}")
    _framelift_parse_version(_version "${_plugin_version}" "${target}")
    _framelift_json_required_string(_abi "${_plugin_json}" "abi" "${target}")
    _framelift_parse_abi(_abi "${_abi}" "${target}")
    _framelift_json_required_bool(_plugin_enabled "${_plugin_json}" "enabled" "${target}")
    _framelift_json_string_array(_provides_features "${_plugin_json}" "${target}" provides features)
    _framelift_json_string_array(_requires_plugins "${_plugin_json}" "${target}" requires plugins)
    _framelift_json_string_array(_requires_features "${_plugin_json}" "${target}" requires features)
    _framelift_json_string_array(_optional_plugins "${_plugin_json}" "${target}" optional plugins)
    _framelift_json_string_array(_optional_features "${_plugin_json}" "${target}" optional features)
    _framelift_json_string_array(_platforms "${_plugin_json}" "${target}" platforms)

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_plugin_json_abs}")

    set(_plugin_binary_name "${_plugin_id}")
    string(TOLOWER "${_plugin_binary_name}" _plugin_binary_name)

    set(_build_plugin "${_plugin_enabled}")
    _framelift_current_platform(_current_platform)
    foreach (_declared_platform IN LISTS _platforms)
        if (NOT _declared_platform STREQUAL "windows" AND NOT _declared_platform STREQUAL "linux" AND
            NOT _declared_platform STREQUAL "macos")
            message(WARNING "${target}: plugin '${_plugin_id}' lists unknown platform '${_declared_platform}' (expected windows/linux/macos) - it will never match")
        endif ()
    endforeach ()
    if (_platforms AND NOT _current_platform IN_LIST _platforms)
        message(STATUS "${target}: disabling plugin because it does not support platform '${_current_platform}'")
        set(_build_plugin FALSE)
    endif ()

    # Emit the plugin metadata JSON embedded by Q_PLUGIN_METADATA(... FILE ...).
    # The host reads it via QPluginLoader::metaData()["MetaData"] without loading the
    # plugin.
    _framelift_json_string(_plugin_id_json "${_plugin_id}")
    _framelift_json_string(_plugin_file_json "${_plugin_binary_name}")
    _framelift_json_string(_plugin_name_json "${_plugin_name}")
    _framelift_json_optional_string_or_null(_plugin_publisher_json "${_plugin_publisher}")
    _framelift_json_optional_string_or_null(_plugin_description_json "${_plugin_description}")
    _framelift_json_string_array_expr(_provides_expr "${_provides_features}")
    _framelift_json_string_array_expr(_requires_plugins_expr "${_requires_plugins}")
    _framelift_json_string_array_expr(_requires_features_expr "${_requires_features}")
    _framelift_json_string_array_expr(_optional_plugins_expr "${_optional_plugins}")
    _framelift_json_string_array_expr(_optional_features_expr "${_optional_features}")
    _framelift_json_string_array_expr(_platforms_expr "${_platforms}")
    if (_plugin_enabled)
        set(_enabled_json "true")
    else ()
        set(_enabled_json "false")
    endif ()

    set(_json "{\n")
    string(APPEND _json "  \"abi\": ${_abi},\n")
    string(APPEND _json "  \"pluginId\": ${_plugin_id_json},\n")
    string(APPEND _json "  \"pluginFile\": ${_plugin_file_json},\n")
    string(APPEND _json "  \"name\": ${_plugin_name_json},\n")
    string(APPEND _json "  \"version\": [${_version_MAJOR}, ${_version_MINOR}, ${_version_PATCH}],\n")
    string(APPEND _json "  \"publisher\": ${_plugin_publisher_json},\n")
    string(APPEND _json "  \"description\": ${_plugin_description_json},\n")
    string(APPEND _json "  \"enabled\": ${_enabled_json},\n")
    string(APPEND _json "  \"providesFeatures\": ${_provides_expr},\n")
    string(APPEND _json "  \"requiresPlugins\": ${_requires_plugins_expr},\n")
    string(APPEND _json "  \"requiresFeatures\": ${_requires_features_expr},\n")
    string(APPEND _json "  \"optionalPlugins\": ${_optional_plugins_expr},\n")
    string(APPEND _json "  \"optionalFeatures\": ${_optional_features_expr},\n")
    string(APPEND _json "  \"platforms\": ${_platforms_expr}\n")
    string(APPEND _json "}\n")

    set(_metadata_json "${CMAKE_CURRENT_BINARY_DIR}/${target}PluginMetadata.json")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    file(WRITE "${_metadata_json}" "${_json}")

    set(${out_header} "${_metadata_json}" PARENT_SCOPE)
    set(${out_enabled} "${_build_plugin}" PARENT_SCOPE)
    set(${out_plugin_id} "${_plugin_id}" PARENT_SCOPE)
    set(${out_plugin_binary_name} "${_plugin_binary_name}" PARENT_SCOPE)
endfunction()
