# JSON-authored built-in compile-time module declarations for the host build.
#
# Built-in modules reuse the same module metadata schema as plugin modules, but
# CMake consumes the JSON directly instead of embedding it into a package DLL.

include("${CMAKE_CURRENT_LIST_DIR}/FrameLiftPackageMetadata.cmake")

function(_framelift_builtin_option_name out module_id)
    set(_prefix "FRAMELIFT_MODULE")
    string(REGEX REPLACE "^framelift\\.host\\." "" _suffix "${module_id}")
    string(TOUPPER "${_suffix}" _suffix)
    string(REGEX REPLACE "[^A-Z0-9_]" "_" _suffix "${_suffix}")
    set(${out} "${_prefix}_${_suffix}" PARENT_SCOPE)
endfunction()

function(_framelift_builtin_module_state out module_id)
    get_property(_option GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${module_id}_OPTION")
    if (NOT _option)
        set(${out} "OFF" PARENT_SCOPE)
        return()
    endif ()
    if (${_option})
        set(${out} "ON" PARENT_SCOPE)
    else ()
        set(${out} "OFF" PARENT_SCOPE)
    endif ()
endfunction()

function(_framelift_read_builtin_module module_json)
    get_filename_component(_module_json_abs "${module_json}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if (NOT EXISTS "${_module_json_abs}")
        message(FATAL_ERROR "Built-in module metadata file not found: ${_module_json_abs}")
    endif ()

    file(READ "${_module_json_abs}" _module_json)
    _framelift_json_required_int(_file_version "${_module_json}" "fileVersion" "${_module_json_abs}")
    _framelift_validate_file_version("${_file_version}" "${_module_json_abs}")
    _framelift_json_required_string(_module_id "${_module_json}" "id" "${_module_json_abs}")
    _framelift_json_required_string(_module_name "${_module_json}" "name" "${_module_json_abs}")
    _framelift_json_optional_string(_module_description "${_module_json}" "description" "")
    _framelift_json_required_bool(_module_enabled "${_module_json}" "enabled" "${_module_json_abs}")
    _framelift_json_optional_bool(_module_required "${_module_json}" "required" OFF "${_module_json_abs}")
    _framelift_json_string_array(_provides_features "${_module_json}" "${_module_json_abs}" provides features)
    _framelift_json_string_array(_requires_modules "${_module_json}" "${_module_json_abs}" requires modules)
    _framelift_json_string_array(_requires_features "${_module_json}" "${_module_json_abs}" requires features)
    _framelift_json_string_array(_optional_modules "${_module_json}" "${_module_json_abs}" optional modules)
    _framelift_json_string_array(_optional_features "${_module_json}" "${_module_json_abs}" optional features)
    _framelift_json_string_array(_platforms "${_module_json}" "${_module_json_abs}" platforms)

    if (_module_required AND NOT _module_enabled)
        message(FATAL_ERROR
                "Built-in module '${_module_id}' is required but is disabled in ${_module_json_abs}")
    endif ()

    _framelift_current_platform(_current_platform)
    set(_module_available TRUE)
    set(_module_reason "")
    if (_platforms AND NOT _current_platform IN_LIST _platforms)
        set(_module_available FALSE)
        set(_module_reason "unsupported platform '${_current_platform}'")
    endif ()
    if (_module_required AND NOT _module_available)
        message(FATAL_ERROR
                "Built-in module '${_module_id}' is required but ${_module_reason}")
    endif ()

    _framelift_builtin_option_name(_module_option "${_module_id}")

    # The JSON `enabled` flag is the default; forks can override a module from the
    # command line (e.g. -DFRAMELIFT_MODULE_GRAPHICS_VULKAN=OFF) for a lean build.
    if (_module_enabled)
        set(_module_default ON)
    else ()
        set(_module_default OFF)
    endif ()
    set(${_module_option} "${_module_default}" CACHE BOOL
            "Enable built-in FrameLift module ${_module_id}")

    # Platform availability is a hard constraint: a module unsupported on this
    # platform is always off, regardless of the option/override.
    if (NOT _module_available)
        set(${_module_option} OFF CACHE BOOL
                "Enable built-in FrameLift module ${_module_id}" FORCE)
    endif ()

    # A required module may not be disabled (by JSON authoring or by override).
    if (_module_required AND NOT ${_module_option})
        message(FATAL_ERROR
                "Built-in module '${_module_id}' is required and cannot be disabled")
    endif ()

    get_property(_module_ids GLOBAL PROPERTY FRAMELIFT_BUILTIN_MODULES)
    if (NOT _module_id IN_LIST _module_ids)
        set_property(GLOBAL APPEND PROPERTY FRAMELIFT_BUILTIN_MODULES "${_module_id}")
    endif ()
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_FILE" "${_module_json_abs}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_OPTION" "${_module_option}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_NAME" "${_module_name}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_DESCRIPTION" "${_module_description}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_REQUIRED" "${_module_required}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_REQUIRES_MODULES" "${_requires_modules}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_REQUIRES_FEATURES" "${_requires_features}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_PROVIDES_FEATURES" "${_provides_features}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_OPTIONAL_MODULES" "${_optional_modules}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_OPTIONAL_FEATURES" "${_optional_features}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_PLATFORMS" "${_platforms}")
    set_property(GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_DISABLED_REASON" "${_module_reason}")
endfunction()

function(framelift_load_builtin_modules root)
    get_filename_component(_root_abs "${root}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if (NOT EXISTS "${_root_abs}")
        message(FATAL_ERROR "Built-in module metadata root not found: ${_root_abs}")
    endif ()

    set_property(GLOBAL PROPERTY FRAMELIFT_BUILTIN_MODULES)
    if (CMAKE_SCRIPT_MODE_FILE)
        file(GLOB_RECURSE _module_json_files "${_root_abs}/*.Module.json")
    else ()
        file(GLOB_RECURSE _module_json_files CONFIGURE_DEPENDS
                "${_root_abs}/*.Module.json")
    endif ()
    list(SORT _module_json_files)
    if (NOT _module_json_files)
        message(FATAL_ERROR "No built-in module metadata files found under ${_root_abs}")
    endif ()
    foreach (_module_json IN LISTS _module_json_files)
        if (NOT CMAKE_SCRIPT_MODE_FILE)
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_module_json}")
        endif ()
        _framelift_read_builtin_module("${_module_json}")
    endforeach ()
    framelift_validate_builtin_modules()
endfunction()

function(framelift_validate_builtin_modules)
    get_property(_module_ids GLOBAL PROPERTY FRAMELIFT_BUILTIN_MODULES)
    foreach (_module_id IN LISTS _module_ids)
        _framelift_builtin_module_state(_module_state "${_module_id}")
        if (NOT _module_state)
            continue()
        endif ()

        get_property(_requires_modules GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_REQUIRES_MODULES")
        foreach (_required_module IN LISTS _requires_modules)
            if (NOT _required_module IN_LIST _module_ids)
                message(FATAL_ERROR
                        "Built-in module '${_module_id}' requires unknown module '${_required_module}'")
            endif ()
            _framelift_builtin_module_state(_required_state "${_required_module}")
            if (NOT _required_state)
                message(FATAL_ERROR
                        "Built-in module '${_module_id}' requires disabled module '${_required_module}'")
            endif ()
        endforeach ()
    endforeach ()
endfunction()

function(framelift_report_builtin_modules)
    get_property(_module_ids GLOBAL PROPERTY FRAMELIFT_BUILTIN_MODULES)
    if (NOT _module_ids)
        return()
    endif ()

    message(STATUS "FrameLift built-in modules:")
    foreach (_module_id IN LISTS _module_ids)
        get_property(_module_option GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_OPTION")
        get_property(_module_name GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_NAME")
        get_property(_module_description GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_DESCRIPTION")
        get_property(_module_required GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_REQUIRED")
        get_property(_requires_modules GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_REQUIRES_MODULES")
        get_property(_disabled_reason GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_DISABLED_REASON")

        _framelift_builtin_module_state(_module_state "${_module_id}")
        if (_module_state)
            set(_state_label "ON")
        else ()
            set(_state_label "OFF")
        endif ()

        set(_details)
        if (_module_required)
            list(APPEND _details "required")
        endif ()
        if (_requires_modules)
            list(JOIN _requires_modules ", " _requires_text)
            list(APPEND _details "requires ${_requires_text}")
        endif ()
        if (_disabled_reason)
            list(APPEND _details "${_disabled_reason}")
        endif ()

        set(_detail_text "")
        if (_details)
            list(JOIN _details "; " _detail_text)
            set(_detail_text " [${_detail_text}]")
        endif ()
        message(STATUS "  ${_module_name}: ${_state_label} (${_module_option})${_detail_text} - ${_module_description}")
    endforeach ()
endfunction()

function(framelift_apply_builtin_module_definitions target)
    get_property(_module_ids GLOBAL PROPERTY FRAMELIFT_BUILTIN_MODULES)
    foreach (_module_id IN LISTS _module_ids)
        get_property(_module_option GLOBAL PROPERTY "FRAMELIFT_BUILTIN_MODULE_${_module_id}_OPTION")
        _framelift_builtin_module_state(_module_state "${_module_id}")
        if (_module_state)
            target_compile_definitions(${target} PRIVATE "${_module_option}=1")
        else ()
            target_compile_definitions(${target} PRIVATE "${_module_option}=0")
        endif ()
    endforeach ()
endfunction()
